---

###
#
# Documentation: http://securitymonkey.readthedocs.io/en/latest/index.html
#                http://securitymonkey.readthedocs.io/en/latest/docker.html
#
###

version: '2'
services:
  api:
    image: "${SECURITY_MONKEY_ECS_IMAGE}:latest"
    environment:
      ECS_BUILD_TIME: "${ECS_BUILD_TIME}"
    env_file:
      - secmonkey.env
      - secmonkey.local.env
    entrypoint: ["/usr/local/src/security_monkey/docker/api-start.sh"]
    logging:
      driver: awslogs
      options:
        awslogs-group: "${SECURITY_MONKEY_ECS_AWSLOGS_GROUP}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: "api"
    mem_limit: 512m
  nginx:
    image: "${SECURITY_MONKEY_ECS_NGINX_IMAGE}:latest"
    working_dir: /etc/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - api:smapi
    logging:
      driver: awslogs
      options:
        awslogs-group: "${SECURITY_MONKEY_ECS_AWSLOGS_GROUP}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: "nginx"
    mem_limit: 64m