---

###
#
# Documentation: http://securitymonkey.readthedocs.io/en/latest/index.html
#                http://securitymonkey.readthedocs.io/en/latest/docker.html
#
###

version: '2'
services:
  scheduler:
    image: "${SECURITY_MONKEY_ECS_IMAGE}:latest"
    env_file:
      - secmonkey.env
      - secmonkey.local.env
    entrypoint: ["/usr/local/src/security_monkey/docker/scheduler-start.sh"]
    logging:
      driver: awslogs
      options:
        awslogs-group: "${SECURITY_MONKEY_ECS_AWSLOGS_GROUP}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: "scheduler"
    mem_limit: 128m